const foods = [
  "Açaí Bowl",
  "Adobo",
  "Affogato",
  "Agedashi Tofu",
  "Aioli Fries",
  "Albondigas",
  "Alfredo Pasta",
  "All-American Burger",
  "All-You-Can-Eat Sushi",
  "Almond Biscotti",
  "Almond Butter Toast",
  "Almond Cake",
  "Almond Croissant",
  "Almond Danish",
  "Almond Macaron",
  "Aloo Gobi",
  "Aloo Paratha",
  "Aloo Tikki",
  "Al Pastor Burrito",
  "Al Pastor Fries",
  "Al Pastor Quesadilla",
  "Al Pastor Taco",
  "American Breakfast",
  "American Cheese Pizza",
  "American Chop Suey",
  "Anchovy Pizza",
  "Angel Food Cake",
  "Animal Fries",
  "Anpan",
  "Antipasto",
  "Antipasto Salad",
  "Apple Bread",
  "Apple Cobbler",
  "Apple Crisp",
  "Apple Danish",
  "Apple Fritter",
  "Apple Pie",
  "Apple Strudel",
  "Apricot Danish",
  "Apricot Tart",
  "Arancini",
  "Arroz Con Pollo",
  "Arroz Caldo",
  "Artichoke Dip",
  "Artisan Pizza",
  "Asada Fries",
  "Asada Nachos",
  "Asian Chicken Salad",
  "Asparagus Soup",
  "Avocado Burger",
  "Avocado Roll",
  "Avocado Salad",
  "Avocado Toast",
  "Baba Ganoush",
  "Baby Back Ribs",
  "Bacon Cheeseburger",
  "Bacon Egg and Cheese",
  "Bacon Pizza",
  "Bagel",
  "Bagel Sandwich",
  "Baguette",
  "Baked Alaska",
  "Baked Beans",
  "Baked Brie",
  "Baked Chicken",
  "Baked Cod",
  "Baked Mac and Cheese",
  "Baked Potato",
  "Baked Salmon",
  "Baklava",
  "Baloney Sandwich",
  "Balsamic Chicken",
  "Balsamic Salad",
  "Banana Bread",
  "Banana Cream Pie",
  "Banana Pancakes",
  "Banana Pudding",
  "Banana Split",
  "Bangers and Mash",
  "Banh Mi",
  "Barbacoa Burrito",
  "Barbacoa Taco",
  "Barbecue Burger",
  "Barbecue Chicken",
  "Barbecue Pizza",
  "Barbecue Pork",
  "Barbecue Ribs",
  "Barbecue Sandwich",
  "Barley Soup",
  "Basmati Rice",
  "Basil Chicken",
  "Basil Fried Rice",
  "Basil Pasta",
  "Basmati Pilaf",
  "BBQ Bacon Burger",
  "BBQ Beef Pizza",
  "BBQ Brisket",
  "BBQ Chicken Pizza",
  "BBQ Pork Sandwich",
  "BBQ Pulled Pork",
  "BBQ Ribs",
  "BBQ Wings",
  "Bean and Cheese Burrito",
  "Bean Burrito",
  "Bean Dip",
  "Bean Soup",
  "Beef and Broccoli",
  "Beef Burrito",
  "Beef Chili",
  "Beef Curry",
  "Beef Enchiladas",
  "Beef Fried Rice",
  "Beef Lo Mein",
  "Beef Noodles",
  "Beef Pho",
  "Beef Pot Pie",
  "Beef Quesadilla",
  "Beef Ramen",
  "Beef Shawarma",
  "Beef Stew",
  "Beef Stroganoff",
  "Beef Taco",
  "Beef Teriyaki",
  "Beef Wellington",
  "Beer Battered Fish",
  "Beet Salad",
  "Belgian Waffle",
  "Berry Crepes",
  "Berry Smoothie",
  "Bibimbap",
  "Big Breakfast",
  "Biryani",
  "Biscuit Sandwich",
  "Biscuits and Gravy",
  "Bison Burger",
  "Black Bean Burger",
  "Black Bean Soup",
  "Black Forest Cake",
  "Blackened Chicken",
  "Blackened Salmon",
  "BLT Sandwich",
  "Blueberry Bagel",
  "Blueberry Cheesecake",
  "Blueberry Cobbler",
  "Blueberry Donut",
  "Blueberry Muffin",
  "Blueberry Pancakes",
  "Blueberry Pie",
  "Blueberry Smoothie",
  "Boba Milk Tea",
  "Boba Tea",
  "Bolognese",
  "Boneless Wings",
  "Boston Cream Donut",
  "Bow Tie Pasta",
  "Bratwurst",
  "Bread Bowl Soup",
  "Bread Pudding",
  "Breadsticks",
  "Breakfast Bagel",
  "Breakfast Bowl",
  "Breakfast Burrito",
  "Breakfast Pizza",
  "Breakfast Quesadilla",
  "Breakfast Sandwich",
  "Brisket Sandwich",
  "Broccoli Beef",
  "Broccoli Cheddar Soup",
  "Broccoli Salad",
  "Broccoli Soup",
  "Brown Rice",
  "Brownie",
  "Brownie Sundae",
  "Bruschetta",
  "Bubble Waffle",
  "Buffalo Burger",
  "Buffalo Cauliflower",
  "Buffalo Chicken Dip",
  "Buffalo Chicken Pizza",
  "Buffalo Chicken Sandwich",
  "Buffalo Wings",
  "Bulgogi",
  "Burger",
  "Burger Bowl",
  "Burger Sliders",
  "Burrata Pizza",
  "Burrito",
  "Burrito Bowl",
  "Butter Chicken",
  "Butter Naan",
  "Butter Pasta",
  "Butter Shrimp",
  "Buttered Corn",
  "Buttermilk Pancakes",
  "Butternut Squash Soup",
  "Cabbage Rolls",
  "Cabbage Soup",
  "Cacio e Pepe",
  "Caesar Salad",
  "Cajun Chicken",
  "Cajun Fries",
  "Cajun Pasta",
  "Cajun Shrimp",
  "Calamari",
  "Calamari Rings",
  "California Roll",
  "Calzone",
  "Camembert",
  "Campfire Potatoes",
  "Cannelloni",
  "Cannoli",
  "Cantaloupe",
  "Capellini",
  "Caprese Panini",
  "Caprese Salad",
  "Caprese Sandwich",
  "Caramel Apple",
  "Caramel Brownie",
  "Caramel Cheesecake",
  "Caramel Frappé",
  "Caramel Ice Cream",
  "Caramel Latte",
  "Caramel Macchiato",
  "Caramel Popcorn",
  "Caramel Sundae",
  "Carbonara",
  "Carne Asada",
  "Carne Asada Burrito",
  "Carne Asada Fries",
  "Carne Asada Nachos",
  "Carne Asada Quesadilla",
  "Carne Asada Taco",
  "Carrot Cake",
  "Carrot Muffin",
  "Carrot Soup",
  "Cashew Chicken",
  "Cashew Shrimp",
  "Catfish",
  "Catfish Po' Boy",
  "Cauliflower Bites",
  "Cauliflower Pizza",
  "Cauliflower Soup",
  "Caviar",
  "Ceviche",
  "Chai Latte",
  "Chana Masala",
  "Char Siu",
  "Charcuterie Board",
  "Cheddar Biscuit",
  "Cheddar Soup",
  "Cheese Bagel",
  "Cheese Bread",
  "Cheese Burger",
  "Cheese Calzone",
  "Cheese Curds",
  "Cheese Danish",
  "Cheese Fries",
  "Cheese Garlic Bread",
  "Cheese Omelet",
  "Cheese Pizza",
  "Cheese Quesadilla",
  "Cheese Ravioli",
  "Cheese Sticks",
  "Cheeseburger",
  "Cheeseburger Sliders",
  "Cheesecake",
  "Cheesecake Bites",
  "Cheesy Bread",
  "Cheesy Fries",
  "Cheesy Potatoes",
  "Chef Salad",
  "Cherry Cheesecake",
  "Cherry Cobbler",
  "Cherry Danish",
  "Cherry Pie",
  "Cherry Turnover",
  "Chicken Alfredo",
  "Chicken and Dumplings",
  "Chicken Bacon Ranch Pizza",
  "Chicken Biscuit",
  "Chicken Bowl",
  "Chicken Broccoli Alfredo",
  "Chicken Burger",
  "Chicken Caesar Salad",
  "Chicken Carbonara",
  "Chicken Chow Mein",
  "Chicken Club",
  "Chicken Curry",
  "Chicken Enchiladas",
  "Chicken Fajitas",
  "Chicken Fried Rice",
  "Chicken Fried Steak",
  "Chicken Gyro",
  "Chicken Katsu",
  "Chicken Lo Mein",
  "Chicken Marsala",
  "Chicken Noodle Soup",
  "Chicken Nuggets",
  "Chicken Pad Thai",
  "Chicken Parmesan",
  "Chicken Parm Sandwich",
  "Chicken Pho",
  "Chicken Pizza",
  "Chicken Pot Pie",
  "Chicken Quesadilla",
  "Chicken Ramen",
  "Chicken Salad",
  "Chicken Salad Sandwich",
  "Chicken Sandwich",
  "Chicken Satay",
  "Chicken Shawarma",
  "Chicken Stir Fry",
  "Chicken Tacos",
  "Chicken Tenders",
  "Chicken Teriyaki",
  "Chicken Tortilla Soup",
  "Chicken Wings",
  "Chickpea Curry",
  "Chickpea Salad",
  "Chili",
  "Chili Cheese Dog",
  "Chili Cheese Fries",
  "Chili Cheese Burger",
  "Chili Mac",
  "Chili Nachos",
  "Chimichanga",
  "Chipotle Burrito",
  "Chipotle Bowl",
  "Chipotle Chicken",
  "Chipotle Steak",
  "Chocolate Cake",
  "Chocolate Chip Cookie",
  "Chocolate Chip Muffin",
  "Chocolate Croissant",
  "Chocolate Donut",
  "Chocolate Eclair",
  "Chocolate Ice Cream",
  "Chocolate Lava Cake",
  "Chocolate Milkshake",
  "Chocolate Mousse",
  "Chocolate Sundae",
  "Chow Fun",
  "Chow Mein",
  "Churros",
  "Ciabatta",
  "Cinnamon Bagel",
  "Cinnamon Bun",
  "Cinnamon Roll",
  "Clam Chowder",
  "Club Sandwich",
  "Cobb Salad",
  "Coconut Chicken",
  "Coconut Curry",
  "Coconut Rice",
  "Coffee Cake",
  "Coleslaw",
  "Combo Pizza",
  "Congee",
  "Cookie Dough Ice Cream",
  "Cookies",
  "Cookies and Cream Ice Cream",
  "Corn Bread",
  "Corn Chowder",
  "Corn Dog",
  "Corn on the Cob",
  "Cornbread",
  "Country Fried Steak",
  "Couscous",
  "Crab Cakes",
  "Crab Rangoon",
  "Crab Roll",
  "Crab Salad",
  "Crackers",
  "Cranberry Muffin",
  "Cranberry Salad",
  "Cream Cheese Bagel",
  "Cream Cheese Wonton",
  "Cream of Mushroom Soup",
  "Creamy Tomato Soup",
  "Crepe",
  "Crispy Chicken Sandwich",
  "Croissant",
  "Croque Monsieur",
  "Croutons",
  "Cuban Sandwich",
  "Cupcake",
  "Cup Noodles",
  "Curly Fries",
  "Curry Chicken",
  "Curry Goat",
  "Curry Noodles",
  "Curry Rice",
  "Curry Shrimp",
  "Custard",
  "Daal",
  "Dalgona Coffee",
  "Danish",
  "Dark Chocolate Cake",
  "Date Cake",
  "Deep Dish Pizza",
  "Deep Fried Oreos",
  "Deep Fried Pickles",
  "Denver Omelet",
  "Deviled Eggs",
  "Dim Sum",
  "Dinner Roll",
  "Dirty Rice",
  "Doner Kebab",
  "Donut",
  "Double Bacon Cheeseburger",
  "Double Cheeseburger",
  "Double Chocolate Cookie",
  "Dragon Roll",
  "Drumsticks",
  "Duck Breast",
  "Duck Confit",
  "Duck Fried Rice",
  "Duck Noodles",
  "Dumplings",
  "Durian Ice Cream",
  "Ebi Roll",
  "Eclair",
  "Edamame",
  "Egg Benedict",
  "Egg Bites",
  "Egg Curry",
  "Egg Drop Soup",
  "Egg Fried Rice",
  "Egg Noodles",
  "Egg Roll",
  "Egg Salad",
  "Egg Salad Sandwich",
  "Egg Sandwich",
  "Egg Tart",
  "Eggplant Parmesan",
  "Eggplant Pizza",
  "Eggplant Rollatini",
  "Elote",
  "Empanada",
  "English Muffin",
  "Enchilada",
  "Enchilada Plate",
  "Escargot",
  "Espresso",
  "Espresso Brownie",
  "Espresso Cheesecake",
  "Espresso Martini",
  "Etouffee",
  "Everything Bagel",
  "Falafel",
  "Falafel Bowl",
  "Falafel Plate",
  "Falafel Wrap",
  "Family Pizza",
  "Fettuccine Alfredo",
  "Fettuccine Carbonara",
  "Fettuccine Primavera",
  "Filet Mignon",
  "Fish Burger",
  "Fish Curry",
  "Fish Fry",
  "Fish Sandwich",
  "Fish Sticks",
  "Fish Taco",
  "Fish Tacos",
  "Fish and Chips",
  "Five Cheese Pizza",
  "Flatbread",
  "Flatbread Pizza",
  "Flan",
  "French Bread",
  "French Dip",
  "French Fries",
  "French Onion Soup",
  "French Toast",
  "Fried Calamari",
  "Fried Catfish",
  "Fried Cheese Curds",
  "Fried Chicken",
  "Fried Chicken Sandwich",
  "Fried Dumplings",
  "Fried Egg",
  "Fried Fish",
  "Fried Ice Cream",
  "Fried Mozzarella",
  "Fried Oreos",
  "Fried Pickles",
  "Fried Plantains",
  "Fried Pork Dumplings",
  "Fried Rice",
  "Fried Rice Bowl",
  "Fried Shrimp",
  "Fried Wontons",
  "Fries",
  "Frittata",
  "Frozen Custard",
  "Frozen Yogurt",
  "Fruit Bowl",
  "Fruit Cup",
  "Fruit Salad",
  "Fruit Smoothie",
  "Fudge Brownie",
  "Funnel Cake",
  "Garlic Bread",
  "Garlic Knots",
  "Garlic Naan",
  "Garlic Parmesan Fries",
  "Garlic Parmesan Wings",
  "Garlic Pizza",
  "Garlic Shrimp",
  "Gazpacho",
  "General Tso Chicken",
  "General Tso Shrimp",
  "German Chocolate Cake",
  "Ginger Beef",
  "Ginger Chicken",
  "Ginger Fried Rice",
  "Ginger Noodles",
  "Ginger Pork",
  "Gingerbread",
  "Gingerbread Cookie",
  "Glazed Donut",
  "Gnocchi",
  "Goat Cheese Pizza",
  "Golden Fried Chicken",
  "Goulash",
  "Granola",
  "Granola Bowl",
  "Granola Parfait",
  "Grape Leaves",
  "Greek Fries",
  "Greek Pizza",
  "Greek Salad",
  "Greek Wrap",
  "Green Beans",
  "Green Chicken Curry",
  "Green Curry",
  "Green Salad",
  "Grilled Cheese",
  "Grilled Cheese Sandwich",
  "Grilled Chicken",
  "Grilled Chicken Salad",
  "Grilled Chicken Sandwich",
  "Grilled Fish",
  "Grilled Pork",
  "Grilled Salmon",
  "Grilled Shrimp",
  "Grilled Steak",
  "Grilled Vegetables",
  "Gyro",
  "Gyro Bowl",
  "Gyro Plate",
  "Gyro Wrap",
    "Ham and Cheese Sandwich",
  "Ham Croissant",
  "Ham Omelet",
  "Ham Pizza",
  "Ham Sandwich",
  "Hamburger",
  "Hash Browns",
  "Hash Brown Bowl",
  "Hawaiian Burger",
  "Hawaiian Pizza",
  "Hazelnut Latte",
  "Hazelnut Muffin",
  "Hazelnut Spread Toast",
  "Herb Chicken",
  "Herb Roasted Potatoes",
  "Hibachi Chicken",
  "Hibachi Rice",
  "Hibachi Shrimp",
  "Hibachi Steak",
  "Honey Chicken",
  "Honey Garlic Chicken",
  "Honey Garlic Wings",
  "Honey Ham",
  "Honey Mustard Chicken",
  "Honey Walnut Shrimp",
  "Hot Chocolate",
  "Hot Dog",
  "Hot Honey Pizza",
  "Hot Pastrami Sandwich",
  "Hot Wings",
  "Hummus",
  "Hummus Plate",
  "Hummus Wrap",
  "Hungarian Goulash",
  "Hush Puppies",
  "Ice Cream",
  "Ice Cream Cake",
  "Iced Americano",
  "Iced Coffee",
  "Iced Latte",
  "Iced Matcha Latte",
  "Iced Mocha",
  "Irish Stew",
  "Italian Beef",
  "Italian Bread",
  "Italian Grinder",
  "Italian Hoagie",
  "Italian Pasta Salad",
  "Italian Pizza",
  "Italian Sausage",
  "Italian Sandwich",
  "Italian Sub",
  "Jalapeño Bagel",
  "Jalapeño Burger",
  "Jalapeño Cheddar Bagel",
  "Jalapeño Poppers",
  "Jambalaya",
  "Japanese Curry",
  "Jasmine Rice",
  "Jerk Chicken",
  "Jerk Pork",
  "Jerk Shrimp",
  "Jumbo Shrimp",
  "Kabob",
  "Kale Caesar Salad",
  "Kale Salad",
  "Katsu Curry",
  "Katsu Sandwich",
  "Kebab",
  "Kettle Corn",
  "Key Lime Pie",
  "Kimchi",
  "Kimchi Fried Rice",
  "Kimchi Ramen",
  "King Crab Legs",
  "Kung Pao Beef",
  "Kung Pao Chicken",
  "Kung Pao Shrimp",
  "Lasagna",
  "Lasagna Roll",
  "Lamb Burger",
  "Lamb Chops",
  "Lamb Curry",
  "Lamb Gyro",
  "Lamb Kebab",
  "Lamb Shawarma",
  "Latte",
  "Lemon Cake",
  "Lemon Chicken",
  "Lemon Cheesecake",
  "Lemon Pepper Chicken",
  "Lemon Pepper Wings",
  "Lemon Pie",
  "Lemon Rice",
  "Lemon Tart",
  "Lentil Curry",
  "Lentil Soup",
  "Linguine Alfredo",
  "Linguine with Clam Sauce",
  "Lobster Bisque",
  "Lobster Mac and Cheese",
  "Lobster Roll",
  "Lo Mein",
  "Loaded Baked Potato",
  "Loaded Fries",
  "Loaded Nachos",
  "Loaded Potato Skins",
  "Mac and Cheese",
  "Mac Salad",
  "Macaroni Salad",
  "Macchiato",
  "Mango Chicken",
  "Mango Curry",
  "Mango Smoothie",
  "Mango Sticky Rice",
  "Margherita Pizza",
  "Marinara Pasta",
  "Mashed Potatoes",
  "Meat Lovers Pizza",
  "Meatball Parmesan",
  "Meatball Pizza",
  "Meatball Sandwich",
  "Meatballs",
  "Mediterranean Bowl",
  "Mediterranean Pizza",
  "Mediterranean Salad",
  "Mediterranean Wrap",
  "Minestrone Soup",
  "Mini Corn Dogs",
  "Mini Donuts",
  "Miso Ramen",
  "Miso Soup",
  "Mixed Grill",
  "Mixed Greens Salad",
  "Mocha",
  "Molten Lava Cake",
  "Mongolian Beef",
  "Mongolian Chicken",
  "Mozzarella Sticks",
  "Muffin",
  "Mushroom Burger",
  "Mushroom Pizza",
  "Mushroom Ravioli",
  "Mushroom Risotto",
  "Mushroom Soup",
  "Mushroom Swiss Burger",
  "Mussels",
  "Mustard Chicken",
  "Mutton Curry",
  "Nacho Fries",
  "Nacho Supreme",
  "Nachos",
  "Napa Cabbage Salad",
  "Napoleon Pastry",
  "Nashville Hot Chicken",
  "Nashville Hot Chicken Sandwich",
  "Nasi Goreng",
  "Neapolitan Pizza",
  "New England Clam Chowder",
  "New York Cheesecake",
  "New York Pizza",
  "Nigiri",
  "Noodle Bowl",
  "Noodle Soup",
  "Nutella Crepe",
  "Nutella Pancakes",
  "Nutella Waffle",
  "Oatmeal",
  "Oatmeal Cookie",
  "Okonomiyaki",
  "Olive Burger",
  "Olive Pizza",
  "Onigiri",
  "Onion Bhaji",
  "Onion Rings",
  "Orange Chicken",
  "Orange Beef",
  "Orange Tofu",
  "Oreo Cheesecake",
  "Oreo Milkshake",
  "Oreo Sundae",
  "Oven Roasted Chicken",
  "Oxtail Stew",
  "Pad Kee Mao",
  "Pad See Ew",
  "Pad Thai",
  "Paella",
  "Pak Choi",
  "Pakora",
  "Pancakes",
  "Pancetta Pasta",
  "Panini",
  "Panna Cotta",
  "Papaya Salad",
  "Parmesan Fries",
  "Parmesan Pasta",
  "Parmesan Wings",
  "Pasta",
  "Pasta Primavera",
  "Pastrami Sandwich",
  "Patatas Bravas",
  "Peach Cobbler",
  "Peach Pie",
  "Peach Smoothie",
  "Peanut Butter Cookie",
  "Peanut Butter Milkshake",
  "Peanut Chicken",
  "Pecan Pie",
  "Peking Duck",
  "Pepper Jack Burger",
  "Pepper Steak",
  "Pepperoni Calzone",
  "Pepperoni Pizza",
  "Pesto Chicken",
  "Pesto Pasta",
  "Philly Cheesesteak",
  "Pho",
  "Pickle Fries",
  "Pickle Pizza",
  "Pickles",
  "Pie",
  "Pierogi",
  "Pineapple Fried Rice",
  "Pineapple Pizza",
  "Pineapple Smoothie",
  "Pita",
  "Pita Bread",
  "Pita Chips",
  "Pita Pizza",
  "Pita Wrap",
  "Pizza",
  "Pizza Bagel",
  "Pizza Fries",
  "Pizza Roll",
  "Pizza Rolls",
  "Pizza Slice",
  "Plantain Chips",
  "Plantains",
  "Plum Cake",
  "Po' Boy",
  "Poblano Soup",
  "Poke Bowl",
  "Polenta",
  "Polish Sausage",
  "Popcorn",
  "Popcorn Chicken",
  "Pork Belly",
  "Pork Bun",
  "Pork Chop",
  "Pork Chops",
  "Pork Dumplings",
  "Pork Fried Rice",
  "Pork Lo Mein",
  "Pork Ramen",
  "Pork Ribs",
  "Pork Shawarma",
  "Pork Tacos",
  "Pot Pie",
  "Pot Roast",
  "Pot Sticker",
  "Potato Cakes",
  "Potato Chips",
  "Potato Salad",
  "Potato Skins",
  "Potato Soup",
  "Poutine",
  "Prawn Curry",
  "Pretzel",
  "Prime Rib",
  "Prosciutto Pizza",
  "Pulled Pork",
  "Pulled Pork Burger",
  "Pulled Pork Sandwich",
  "Pumpkin Bread",
  "Pumpkin Cheesecake",
  "Pumpkin Muffin",
  "Pumpkin Pie",
  "Pumpkin Soup",
  "Quesadilla",
  "Quiche",
  "Quinoa Bowl",
  "Quinoa Salad",
  "Ramen",
  "Raspberry Cheesecake",
  "Raspberry Danish",
  "Raspberry Muffin",
  "Raspberry Pie",
  "Raspberry Smoothie",
  "Ravioli",
  "Red Beans and Rice",
  "Red Curry",
  "Red Velvet Cake",
  "Reuben Sandwich",
  "Rice Bowl",
  "Rice Noodles",
  "Rigatoni",
  "Risotto",
  "Roast Beef",
  "Roast Beef Sandwich",
  "Roast Chicken",
  "Roasted Potatoes",
  "Roasted Turkey",
  "Rolls",
  "Rotisserie Chicken",
  "Naan",
  "Nacho Fries",
  "Nacho Supreme",
  "Nachos",
  "Napa Cabbage Salad",
  "Napoleon Pastry",
  "Nashville Hot Chicken",
  "Nashville Hot Chicken Sandwich",
  "Nasi Goreng",
  "Neapolitan Pizza",
  "New England Clam Chowder",
  "New York Cheesecake",
  "New York Pizza",
  "Nigiri",
  "Noodle Bowl",
  "Noodle Soup",
  "Nutella Crepe",
  "Nutella Pancakes",
  "Nutella Waffle",
  "Oatmeal",
  "Oatmeal Cookie",
  "Okonomiyaki",
  "Olive Burger",
  "Olive Pizza",
  "Onigiri",
  "Onion Bhaji",
  "Onion Rings",
  "Orange Chicken",
  "Orange Beef",
  "Orange Tofu",
  "Oreo Cheesecake",
  "Oreo Milkshake",
  "Oreo Sundae",
  "Oven Roasted Chicken",
  "Oxtail Stew",
  "Pad Kee Mao",
  "Pad See Ew",
  "Pad Thai",
  "Paella",
  "Pak Choi",
  "Pakora",
  "Pancakes",
  "Pancetta Pasta",
  "Panini",
  "Panna Cotta",
  "Papaya Salad",
  "Parmesan Fries",
  "Parmesan Pasta",
  "Parmesan Wings",
  "Pasta",
  "Pasta Primavera",
  "Pastrami Sandwich",
  "Patatas Bravas",
  "Peach Cobbler",
  "Peach Pie",
  "Peach Smoothie",
  "Peanut Butter Cookie",
  "Peanut Butter Milkshake",
  "Peanut Chicken",
  "Pecan Pie",
  "Peking Duck",
  "Pepper Jack Burger",
  "Pepper Steak",
  "Pepperoni Calzone",
  "Pepperoni Pizza",
  "Pesto Chicken",
  "Pesto Pasta",
  "Philly Cheesesteak",
  "Pho",
  "Pickle Fries",
  "Pickle Pizza",
  "Pickles",
  "Pie",
  "Pierogi",
  "Pineapple Fried Rice",
  "Pineapple Pizza",
  "Pineapple Smoothie",
  "Pita",
  "Pita Bread",
  "Pita Chips",
  "Pita Pizza",
  "Pita Wrap",
  "Pizza",
  "Pizza Bagel",
  "Pizza Fries",
  "Pizza Roll",
  "Pizza Rolls",
  "Pizza Slice",
  "Plantain Chips",
  "Plantains",
  "Plum Cake",
  "Po' Boy",
  "Poblano Soup",
  "Poke Bowl",
  "Polenta",
  "Polish Sausage",
  "Popcorn",
  "Popcorn Chicken",
  "Pork Belly",
  "Pork Bun",
  "Pork Chop",
  "Pork Chops",
  "Pork Dumplings",
  "Pork Fried Rice",
  "Pork Lo Mein",
  "Pork Ramen",
  "Pork Ribs",
  "Pork Shawarma",
  "Pork Tacos",
  "Pot Pie",
  "Pot Roast",
  "Pot Sticker",
  "Potato Cakes",
  "Potato Chips",
  "Potato Salad",
  "Potato Skins",
  "Potato Soup",
  "Poutine",
  "Prawn Curry",
  "Pretzel",
  "Prime Rib",
  "Prosciutto Pizza",
  "Pulled Pork",
  "Pulled Pork Burger",
  "Pulled Pork Sandwich",
  "Pumpkin Bread",
  "Pumpkin Cheesecake",
  "Pumpkin Muffin",
  "Pumpkin Pie",
  "Pumpkin Soup",
  "Quesadilla",
  "Quiche",
  "Quinoa Bowl",
  "Quinoa Salad",
  "Ramen",
  "Raspberry Cheesecake",
  "Raspberry Danish",
  "Raspberry Muffin",
  "Raspberry Pie",
  "Raspberry Smoothie",
  "Ravioli",
  "Red Beans and Rice",
  "Red Curry",
  "Red Velvet Cake",
  "Reuben Sandwich",
  "Rice Bowl",
  "Rice Noodles",
  "Rigatoni",
  "Risotto",
  "Roast Beef",
  "Roast Beef Sandwich",
  "Roast Chicken",
  "Roasted Potatoes",
  "Roasted Turkey",
  "Rolls",
  "Rotisserie Chicken",
  "Saffron Rice",
  "Sake",
  "Salad",
  "Salmon",
  "Salmon Burger",
  "Salmon Roll",
  "Salmon Teriyaki",
  "Salsa",
  "Samosa",
  "Sandwich",
  "Sashimi",
  "Satay",
  "Sausage",
  "Sausage Pizza",
  "Sausage Roll",
  "Schnitzel",
  "Scallops",
  "Seafood Boil",
  "Seafood Pasta",
  "Seafood Soup",
  "Seaweed Salad",
  "Sesame Chicken",
  "Sesame Noodles",
  "Shakshuka",
  "Shawarma",
  "Shepherd's Pie",
  "Shrimp",
  "Shrimp Fried Rice",
  "Shrimp Scampi",
  "Shrimp Tacos",
  "Shrimp Tempura",
  "Sinigang",
  "Sliders",
  "Smoothie",
  "Soba Noodles",
  "Sofrito",
  "Souvlaki",
  "Spaghetti",
  "Spaghetti Carbonara",
  "Spaghetti Bolognese",
  "Spam Musubi",
  "Spanish Rice",
  "Spare Ribs",
  "Spinach Dip",
  "Spinach Lasagna",
  "Spinach Salad",
  "Spring Rolls",
  "Squash Soup",
  "Steak",
  "Steak Burger",
  "Steak Fajitas",
  "Steak Sandwich",
  "Stir Fry",
  "Strawberry Cake",
  "Strawberry Cheesecake",
  "Strawberry Ice Cream",
  "Strawberry Muffin",
  "Strawberry Smoothie",
  "Stuffed Peppers",
  "Sushi",
  "Sweet Potato Fries",
  "Sweet Potato Pie",
  "Sweet and Sour Chicken",
  "Swiss Burger",
  "Szechuan Chicken",
  "Tacos",
  "Taco Salad",
  "Taco Soup",
  "Takoyaki",
  "Tamale",
  "Tamales",
  "Tandoori Chicken",
  "Tapas",
  "Tater Tots",
  "Tempura",
  "Teriyaki Chicken",
  "Teriyaki Salmon",
  "Texas Toast",
  "Thai Curry",
  "Thai Noodles",
  "Thai Tea",
  "Tikka Masala",
  "Tiramisu",
  "Tofu",
  "Tofu Bowl",
  "Tom Yum Soup",
  "Tomato Pasta",
  "Tomato Soup",
  "Tonkatsu",
  "Tortellini",
  "Tortilla Chips",
  "Tostada",
  "Trail Mix",
  "Tres Leches Cake",
  "Truffle Fries",
  "Tuna",
  "Tuna Salad",
  "Tuna Sandwich",
  "Tuna Sushi",
  "Turkey Burger",
  "Turkey Sandwich",
  "Turkey Soup",
  "Udon",
  "Udon Soup",
  "Ugali",
  "Unagi",
  "Upside Down Cake",
  "Vada Pav",
  "Vanilla Cake",
  "Vanilla Ice Cream",
  "Vanilla Milkshake",
  "Vegetable Curry",
  "Vegetable Fried Rice",
  "Vegetable Lasagna",
  "Vegetable Pizza",
  "Vegetable Soup",
  "Veggie Burger",
  "Veggie Wrap",
  "Vermicelli",
  "Vindaloo",
  "Waffles",
  "Walnut Cake",
  "Wasabi Peas",
  "Watermelon Salad",
  "Wedding Cake",
  "Wellington",
  "White Chocolate Cheesecake",
  "White Pizza",
  "Whole Wheat Bread",
  "Wonton Soup",
  "Wrap",
  "Wurst",
  "Xacuti",
  "Xiao Long Bao",
  "Xnipec",
  "Yakitori",
  "Yaki Udon",
  "Yakisoba",
  "Yam Fries",
  "Yellow Curry",
  "Yogurt",
  "Yogurt Parfait",
  "Ziti",
  "Ziti Pasta",
  "Zucchini Bread",
  "Zucchini Fries",
  "Zucchini Noodles",
  "Zucchini Pizza"
];